// Package components provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package components

// Defines values for ProtocolType.
const (
	Coap    ProtocolType = "coap"
	CoapTcp ProtocolType = "coap+tcp"
	Http    ProtocolType = "http"
	Https   ProtocolType = "https"
	Rest    ProtocolType = "rest"
	Tcp     ProtocolType = "tcp"
	Tls     ProtocolType = "tls"
)

// Valid indicates whether the value is a known member of the ProtocolType enum.
func (e ProtocolType) Valid() bool {
	switch e {
	case Coap:
		return true
	case CoapTcp:
		return true
	case Http:
		return true
	case Https:
		return true
	case Rest:
		return true
	case Tcp:
		return true
	case Tls:
		return true
	default:
		return false
	}
}

// Defines values for RVDirectiveMedium.
const (
	EthAll  RVDirectiveMedium = "eth_all"
	WifiAll RVDirectiveMedium = "wifi_all"
)

// Valid indicates whether the value is a known member of the RVDirectiveMedium enum.
func (e RVDirectiveMedium) Valid() bool {
	switch e {
	case EthAll:
		return true
	case WifiAll:
		return true
	default:
		return false
	}
}

// DNSHostname defines model for DNSHostname.
type DNSHostname = string

// Error defines model for Error.
type Error struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

// ErrorString A human-readable error message.
type ErrorString = string

// IPv4Address defines model for IPv4Address.
type IPv4Address = string

// PortNumber defines model for PortNumber.
type PortNumber = int

// PortString defines model for PortString.
type PortString = string

// ProtocolType Protocol to use for communication:
// - `rest` - RESTful HTTP/HTTPS
// - `http` - HTTP protocol
// - `https` - HTTPS protocol (recommended for production)
// - `tcp` - Raw TCP connection
// - `tls` - TLS-secured TCP connection
// - `coap+tcp` - CoAP over TCP
// - `coap` - Constrained Application Protocol
type ProtocolType string

// RVDirective A single rendezvous directive containing connection parameters.
// At least one of `dns` or `ip` must be specified.
type RVDirective struct {
	// ClCertHash Client certificate hash for validation (SHA-256 or SHA-384 hex string)
	ClCertHash *string `json:"cl_cert_hash,omitempty"`

	// DelaySeconds Delay in seconds before attempting connection (with up to 25% randomization)
	DelaySeconds *uint32 `json:"delay_seconds,omitempty"`

	// DevOnly Instruction applies to device only (not owner)
	DevOnly    *bool        `json:"dev_only,omitempty"`
	DevicePort *PortString  `json:"device_port,omitempty"`
	Dns        *DNSHostname `json:"dns,omitempty"`

	// ExtRv Extended rendezvous information for custom device-specific instructions
	ExtRv *string      `json:"ext_rv,omitempty"`
	Ip    *IPv4Address `json:"ip,omitempty"`

	// Medium Network medium/interface to use for communication.
	// Options: eth_all, wifi_all
	Medium *RVDirectiveMedium `json:"medium,omitempty"`

	// OwnerOnly Instruction applies to owner only (not device)
	OwnerOnly *bool       `json:"owner_only,omitempty"`
	OwnerPort *PortString `json:"owner_port,omitempty"`

	// Protocol Protocol to use for communication:
	// - `rest` - RESTful HTTP/HTTPS
	// - `http` - HTTP protocol
	// - `https` - HTTPS protocol (recommended for production)
	// - `tcp` - Raw TCP connection
	// - `tls` - TLS-secured TCP connection
	// - `coap+tcp` - CoAP over TCP
	// - `coap` - Constrained Application Protocol
	Protocol *ProtocolType `json:"protocol,omitempty"`

	// RvBypass Bypass rendezvous server and connect directly to owner
	RvBypass *bool `json:"rv_bypass,omitempty"`

	// SvCertHash Server certificate hash for validation (SHA-256 or SHA-384 hex string)
	SvCertHash *string `json:"sv_cert_hash,omitempty"`

	// UserInput User input configuration
	UserInput *string `json:"user_input,omitempty"`

	// WifiPw WiFi network password
	WifiPw *string `json:"wifi_pw,omitempty"`

	// WifiSsid WiFi network SSID (Service Set Identifier)
	WifiSsid *string `json:"wifi_ssid,omitempty"`
}

// RVDirectiveMedium Network medium/interface to use for communication.
// Options: eth_all, wifi_all
type RVDirectiveMedium string

// RVInfo Rendezvous information array containing one or more rendezvous directive objects.
// Each object contains fields that guide devices and owners on how to connect to
// the rendezvous server, including network configuration, protocols, and connection parameters.
//
// Processing behavior (FDO specification section 3.7):
// - Directives are processed in order (index 0 first, then 1, etc.)
// - The first successful connection to a rendezvous server MAY be used
// - Multiple directives provide fallback options for device connectivity
// - At least one of `dns` or `ip` must be specified for each directive
//
// Format: Array of objects with flat key-value pairs (legacy v1 format for backward compatibility).
type RVInfo = []RVDirective

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error
