//go:build go1.22

// Package rvto2addr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rvto2addr

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for RVTO2AddrEntryProtocol.
const (
	Http  RVTO2AddrEntryProtocol = "http"
	Https RVTO2AddrEntryProtocol = "https"
)

// RVTO2Addr defines model for RVTO2Addr.
type RVTO2Addr = []RVTO2AddrEntry

// RVTO2AddrEntry defines model for RVTO2AddrEntry.
type RVTO2AddrEntry struct {
	Dns      *string                 `json:"dns,omitempty"`
	Ip       *string                 `json:"ip,omitempty"`
	Port     *int                    `json:"port,omitempty"`
	Protocol *RVTO2AddrEntryProtocol `json:"protocol,omitempty"`
}

// RVTO2AddrEntryProtocol defines model for RVTO2AddrEntry.Protocol.
type RVTO2AddrEntryProtocol string

// PostRvto2addrJSONRequestBody defines body for PostRvto2addr for application/json ContentType.
type PostRvto2addrJSONRequestBody = RVTO2Addr

// PutRvto2addrJSONRequestBody defines body for PutRvto2addr for application/json ContentType.
type PutRvto2addrJSONRequestBody = RVTO2Addr

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /rvto2addr)
	DeleteRvto2addr(w http.ResponseWriter, r *http.Request)

	// (GET /rvto2addr)
	GetRvto2addr(w http.ResponseWriter, r *http.Request)

	// (POST /rvto2addr)
	PostRvto2addr(w http.ResponseWriter, r *http.Request)

	// (PUT /rvto2addr)
	PutRvto2addr(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteRvto2addr operation middleware
func (siw *ServerInterfaceWrapper) DeleteRvto2addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRvto2addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRvto2addr operation middleware
func (siw *ServerInterfaceWrapper) GetRvto2addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRvto2addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRvto2addr operation middleware
func (siw *ServerInterfaceWrapper) PostRvto2addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRvto2addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutRvto2addr operation middleware
func (siw *ServerInterfaceWrapper) PutRvto2addr(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutRvto2addr(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/rvto2addr", wrapper.DeleteRvto2addr)
	m.HandleFunc("GET "+options.BaseURL+"/rvto2addr", wrapper.GetRvto2addr)
	m.HandleFunc("POST "+options.BaseURL+"/rvto2addr", wrapper.PostRvto2addr)
	m.HandleFunc("PUT "+options.BaseURL+"/rvto2addr", wrapper.PutRvto2addr)

	return m
}

type DeleteRvto2addrRequestObject struct {
}

type DeleteRvto2addrResponseObject interface {
	VisitDeleteRvto2addrResponse(w http.ResponseWriter) error
}

type DeleteRvto2addr200JSONResponse RVTO2Addr

func (response DeleteRvto2addr200JSONResponse) VisitDeleteRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRvto2addr401JSONResponse struct{ externalRef0.Unauthorized }

func (response DeleteRvto2addr401JSONResponse) VisitDeleteRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRvto2addr403JSONResponse struct{ externalRef0.Forbidden }

func (response DeleteRvto2addr403JSONResponse) VisitDeleteRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRvto2addr500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response DeleteRvto2addr500JSONResponse) VisitDeleteRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRvto2addrRequestObject struct {
}

type GetRvto2addrResponseObject interface {
	VisitGetRvto2addrResponse(w http.ResponseWriter) error
}

type GetRvto2addr200JSONResponse RVTO2Addr

func (response GetRvto2addr200JSONResponse) VisitGetRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRvto2addr401JSONResponse struct{ externalRef0.Unauthorized }

func (response GetRvto2addr401JSONResponse) VisitGetRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRvto2addr403JSONResponse struct{ externalRef0.Forbidden }

func (response GetRvto2addr403JSONResponse) VisitGetRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRvto2addr500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response GetRvto2addr500JSONResponse) VisitGetRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostRvto2addrRequestObject struct {
	Body *PostRvto2addrJSONRequestBody
}

type PostRvto2addrResponseObject interface {
	VisitPostRvto2addrResponse(w http.ResponseWriter) error
}

type PostRvto2addr200JSONResponse RVTO2Addr

func (response PostRvto2addr200JSONResponse) VisitPostRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRvto2addr401JSONResponse struct{ externalRef0.Unauthorized }

func (response PostRvto2addr401JSONResponse) VisitPostRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostRvto2addr403JSONResponse struct{ externalRef0.Forbidden }

func (response PostRvto2addr403JSONResponse) VisitPostRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostRvto2addr500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response PostRvto2addr500JSONResponse) VisitPostRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutRvto2addrRequestObject struct {
	Body *PutRvto2addrJSONRequestBody
}

type PutRvto2addrResponseObject interface {
	VisitPutRvto2addrResponse(w http.ResponseWriter) error
}

type PutRvto2addr200JSONResponse RVTO2Addr

func (response PutRvto2addr200JSONResponse) VisitPutRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutRvto2addr401JSONResponse struct{ externalRef0.Unauthorized }

func (response PutRvto2addr401JSONResponse) VisitPutRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutRvto2addr403JSONResponse struct{ externalRef0.Forbidden }

func (response PutRvto2addr403JSONResponse) VisitPutRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutRvto2addr500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response PutRvto2addr500JSONResponse) VisitPutRvto2addrResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (DELETE /rvto2addr)
	DeleteRvto2addr(ctx context.Context, request DeleteRvto2addrRequestObject) (DeleteRvto2addrResponseObject, error)

	// (GET /rvto2addr)
	GetRvto2addr(ctx context.Context, request GetRvto2addrRequestObject) (GetRvto2addrResponseObject, error)

	// (POST /rvto2addr)
	PostRvto2addr(ctx context.Context, request PostRvto2addrRequestObject) (PostRvto2addrResponseObject, error)

	// (PUT /rvto2addr)
	PutRvto2addr(ctx context.Context, request PutRvto2addrRequestObject) (PutRvto2addrResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteRvto2addr operation middleware
func (sh *strictHandler) DeleteRvto2addr(w http.ResponseWriter, r *http.Request) {
	var request DeleteRvto2addrRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRvto2addr(ctx, request.(DeleteRvto2addrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRvto2addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRvto2addrResponseObject); ok {
		if err := validResponse.VisitDeleteRvto2addrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRvto2addr operation middleware
func (sh *strictHandler) GetRvto2addr(w http.ResponseWriter, r *http.Request) {
	var request GetRvto2addrRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRvto2addr(ctx, request.(GetRvto2addrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRvto2addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRvto2addrResponseObject); ok {
		if err := validResponse.VisitGetRvto2addrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRvto2addr operation middleware
func (sh *strictHandler) PostRvto2addr(w http.ResponseWriter, r *http.Request) {
	var request PostRvto2addrRequestObject

	var body PostRvto2addrJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRvto2addr(ctx, request.(PostRvto2addrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRvto2addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRvto2addrResponseObject); ok {
		if err := validResponse.VisitPostRvto2addrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutRvto2addr operation middleware
func (sh *strictHandler) PutRvto2addr(w http.ResponseWriter, r *http.Request) {
	var request PutRvto2addrRequestObject

	var body PutRvto2addrJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutRvto2addr(ctx, request.(PutRvto2addrRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutRvto2addr")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutRvto2addrResponseObject); ok {
		if err := validResponse.VisitPutRvto2addrResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
