// Package rvto2addr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rvto2addr

import (
	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
)

// SetOwnerRedirectJSONRequestBody defines body for SetOwnerRedirect for application/json ContentType.
type SetOwnerRedirectJSONRequestBody = externalRef0.RVTO2Addr
