//go:build go1.22

// Package rvinfo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rvinfo

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for MediumMedium.
const (
	Wifi1    MediumMedium = "wifi_1"
	Wifi2    MediumMedium = "wifi_2"
	Wifi3    MediumMedium = "wifi_3"
	Wifi4    MediumMedium = "wifi_4"
	Wifi5    MediumMedium = "wifi_5"
	Wifi6    MediumMedium = "wifi_6"
	Wifi7    MediumMedium = "wifi_7"
	Wifi8    MediumMedium = "wifi_8"
	Wifi9    MediumMedium = "wifi_9"
	WifiAll  MediumMedium = "wifi_all"
	Wired1   MediumMedium = "wired_1"
	Wired2   MediumMedium = "wired_2"
	Wired3   MediumMedium = "wired_3"
	Wired4   MediumMedium = "wired_4"
	Wired5   MediumMedium = "wired_5"
	Wired6   MediumMedium = "wired_6"
	Wired7   MediumMedium = "wired_7"
	Wired8   MediumMedium = "wired_8"
	Wired9   MediumMedium = "wired_9"
	WiredAll MediumMedium = "wired_all"
)

// Defines values for ProtocolProtocol.
const (
	Coap    ProtocolProtocol = "coap"
	CoapTcp ProtocolProtocol = "coap+tcp"
	Http    ProtocolProtocol = "http"
	Https   ProtocolProtocol = "https"
	Rest    ProtocolProtocol = "rest"
	Tcp     ProtocolProtocol = "tcp"
	Tls     ProtocolProtocol = "tls"
)

// ClCertHash defines model for ClCertHash.
type ClCertHash struct {
	ClCertHash *string `json:"cl_cert_hash,omitempty"`
}

// DNS defines model for DNS.
type DNS struct {
	Dns *string `json:"dns,omitempty"`
}

// DelaySeconds defines model for DelaySeconds.
type DelaySeconds struct {
	DelaySeconds *uint32 `json:"delay_seconds,omitempty"`
}

// DevOnly defines model for DevOnly.
type DevOnly struct {
	DevOnly *bool `json:"dev_only,omitempty"`
}

// DevicePort defines model for DevicePort.
type DevicePort struct {
	DevicePort *int `json:"device_port,omitempty"`
}

// ExtRV defines model for ExtRV.
type ExtRV struct {
	ExtRv *string `json:"ext_rv,omitempty"`
}

// IP defines model for IP.
type IP struct {
	Ip *string `json:"ip,omitempty"`
}

// Medium defines model for Medium.
type Medium struct {
	Medium *MediumMedium `json:"medium,omitempty"`
}

// MediumMedium defines model for Medium.Medium.
type MediumMedium string

// OwnerOnly defines model for OwnerOnly.
type OwnerOnly struct {
	OwnerOnly *bool `json:"owner_only,omitempty"`
}

// OwnerPort defines model for OwnerPort.
type OwnerPort struct {
	OwnerPort *int `json:"owner_port,omitempty"`
}

// Protocol defines model for Protocol.
type Protocol struct {
	Protocol *ProtocolProtocol `json:"protocol,omitempty"`
}

// ProtocolProtocol defines model for Protocol.Protocol.
type ProtocolProtocol string

// RVBypass defines model for RVBypass.
type RVBypass struct {
	RvBypass *bool `json:"rv_bypass,omitempty"`
}

// RVInfo defines model for RVInfo.
type RVInfo = []RVInstruction

// RVInstruction defines model for RVInstruction.
type RVInstruction = []RVInstruction_Item

// RVInstruction_Item defines model for RVInstruction.Item.
type RVInstruction_Item struct {
	union json.RawMessage
}

// SvCertHash defines model for SvCertHash.
type SvCertHash struct {
	SvCertHash *string `json:"sv_cert_hash,omitempty"`
}

// UserInput defines model for UserInput.
type UserInput struct {
	UserInput *string `json:"user_input,omitempty"`
}

// WifiPW defines model for WifiPW.
type WifiPW struct {
	WifiPw *string `json:"wifi_pw,omitempty"`
}

// WifiSSID defines model for WifiSSID.
type WifiSSID struct {
	WifiSsid *string `json:"wifi_ssid,omitempty"`
}

// PostRvinfoJSONRequestBody defines body for PostRvinfo for application/json ContentType.
type PostRvinfoJSONRequestBody = RVInfo

// PutRvinfoJSONRequestBody defines body for PutRvinfo for application/json ContentType.
type PutRvinfoJSONRequestBody = RVInfo

// AsDNS returns the union data inside the RVInstruction_Item as a DNS
func (t RVInstruction_Item) AsDNS() (DNS, error) {
	var body DNS
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDNS overwrites any union data inside the RVInstruction_Item as the provided DNS
func (t *RVInstruction_Item) FromDNS(v DNS) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDNS performs a merge with any union data inside the RVInstruction_Item, using the provided DNS
func (t *RVInstruction_Item) MergeDNS(v DNS) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIP returns the union data inside the RVInstruction_Item as a IP
func (t RVInstruction_Item) AsIP() (IP, error) {
	var body IP
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIP overwrites any union data inside the RVInstruction_Item as the provided IP
func (t *RVInstruction_Item) FromIP(v IP) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIP performs a merge with any union data inside the RVInstruction_Item, using the provided IP
func (t *RVInstruction_Item) MergeIP(v IP) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProtocol returns the union data inside the RVInstruction_Item as a Protocol
func (t RVInstruction_Item) AsProtocol() (Protocol, error) {
	var body Protocol
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProtocol overwrites any union data inside the RVInstruction_Item as the provided Protocol
func (t *RVInstruction_Item) FromProtocol(v Protocol) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProtocol performs a merge with any union data inside the RVInstruction_Item, using the provided Protocol
func (t *RVInstruction_Item) MergeProtocol(v Protocol) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMedium returns the union data inside the RVInstruction_Item as a Medium
func (t RVInstruction_Item) AsMedium() (Medium, error) {
	var body Medium
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMedium overwrites any union data inside the RVInstruction_Item as the provided Medium
func (t *RVInstruction_Item) FromMedium(v Medium) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMedium performs a merge with any union data inside the RVInstruction_Item, using the provided Medium
func (t *RVInstruction_Item) MergeMedium(v Medium) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDevicePort returns the union data inside the RVInstruction_Item as a DevicePort
func (t RVInstruction_Item) AsDevicePort() (DevicePort, error) {
	var body DevicePort
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDevicePort overwrites any union data inside the RVInstruction_Item as the provided DevicePort
func (t *RVInstruction_Item) FromDevicePort(v DevicePort) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDevicePort performs a merge with any union data inside the RVInstruction_Item, using the provided DevicePort
func (t *RVInstruction_Item) MergeDevicePort(v DevicePort) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOwnerPort returns the union data inside the RVInstruction_Item as a OwnerPort
func (t RVInstruction_Item) AsOwnerPort() (OwnerPort, error) {
	var body OwnerPort
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwnerPort overwrites any union data inside the RVInstruction_Item as the provided OwnerPort
func (t *RVInstruction_Item) FromOwnerPort(v OwnerPort) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwnerPort performs a merge with any union data inside the RVInstruction_Item, using the provided OwnerPort
func (t *RVInstruction_Item) MergeOwnerPort(v OwnerPort) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWifiSSID returns the union data inside the RVInstruction_Item as a WifiSSID
func (t RVInstruction_Item) AsWifiSSID() (WifiSSID, error) {
	var body WifiSSID
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWifiSSID overwrites any union data inside the RVInstruction_Item as the provided WifiSSID
func (t *RVInstruction_Item) FromWifiSSID(v WifiSSID) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWifiSSID performs a merge with any union data inside the RVInstruction_Item, using the provided WifiSSID
func (t *RVInstruction_Item) MergeWifiSSID(v WifiSSID) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWifiPW returns the union data inside the RVInstruction_Item as a WifiPW
func (t RVInstruction_Item) AsWifiPW() (WifiPW, error) {
	var body WifiPW
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWifiPW overwrites any union data inside the RVInstruction_Item as the provided WifiPW
func (t *RVInstruction_Item) FromWifiPW(v WifiPW) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWifiPW performs a merge with any union data inside the RVInstruction_Item, using the provided WifiPW
func (t *RVInstruction_Item) MergeWifiPW(v WifiPW) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDevOnly returns the union data inside the RVInstruction_Item as a DevOnly
func (t RVInstruction_Item) AsDevOnly() (DevOnly, error) {
	var body DevOnly
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDevOnly overwrites any union data inside the RVInstruction_Item as the provided DevOnly
func (t *RVInstruction_Item) FromDevOnly(v DevOnly) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDevOnly performs a merge with any union data inside the RVInstruction_Item, using the provided DevOnly
func (t *RVInstruction_Item) MergeDevOnly(v DevOnly) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOwnerOnly returns the union data inside the RVInstruction_Item as a OwnerOnly
func (t RVInstruction_Item) AsOwnerOnly() (OwnerOnly, error) {
	var body OwnerOnly
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwnerOnly overwrites any union data inside the RVInstruction_Item as the provided OwnerOnly
func (t *RVInstruction_Item) FromOwnerOnly(v OwnerOnly) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwnerOnly performs a merge with any union data inside the RVInstruction_Item, using the provided OwnerOnly
func (t *RVInstruction_Item) MergeOwnerOnly(v OwnerOnly) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRVBypass returns the union data inside the RVInstruction_Item as a RVBypass
func (t RVInstruction_Item) AsRVBypass() (RVBypass, error) {
	var body RVBypass
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRVBypass overwrites any union data inside the RVInstruction_Item as the provided RVBypass
func (t *RVInstruction_Item) FromRVBypass(v RVBypass) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRVBypass performs a merge with any union data inside the RVInstruction_Item, using the provided RVBypass
func (t *RVInstruction_Item) MergeRVBypass(v RVBypass) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDelaySeconds returns the union data inside the RVInstruction_Item as a DelaySeconds
func (t RVInstruction_Item) AsDelaySeconds() (DelaySeconds, error) {
	var body DelaySeconds
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDelaySeconds overwrites any union data inside the RVInstruction_Item as the provided DelaySeconds
func (t *RVInstruction_Item) FromDelaySeconds(v DelaySeconds) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDelaySeconds performs a merge with any union data inside the RVInstruction_Item, using the provided DelaySeconds
func (t *RVInstruction_Item) MergeDelaySeconds(v DelaySeconds) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSvCertHash returns the union data inside the RVInstruction_Item as a SvCertHash
func (t RVInstruction_Item) AsSvCertHash() (SvCertHash, error) {
	var body SvCertHash
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSvCertHash overwrites any union data inside the RVInstruction_Item as the provided SvCertHash
func (t *RVInstruction_Item) FromSvCertHash(v SvCertHash) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSvCertHash performs a merge with any union data inside the RVInstruction_Item, using the provided SvCertHash
func (t *RVInstruction_Item) MergeSvCertHash(v SvCertHash) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClCertHash returns the union data inside the RVInstruction_Item as a ClCertHash
func (t RVInstruction_Item) AsClCertHash() (ClCertHash, error) {
	var body ClCertHash
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClCertHash overwrites any union data inside the RVInstruction_Item as the provided ClCertHash
func (t *RVInstruction_Item) FromClCertHash(v ClCertHash) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClCertHash performs a merge with any union data inside the RVInstruction_Item, using the provided ClCertHash
func (t *RVInstruction_Item) MergeClCertHash(v ClCertHash) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserInput returns the union data inside the RVInstruction_Item as a UserInput
func (t RVInstruction_Item) AsUserInput() (UserInput, error) {
	var body UserInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserInput overwrites any union data inside the RVInstruction_Item as the provided UserInput
func (t *RVInstruction_Item) FromUserInput(v UserInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserInput performs a merge with any union data inside the RVInstruction_Item, using the provided UserInput
func (t *RVInstruction_Item) MergeUserInput(v UserInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExtRV returns the union data inside the RVInstruction_Item as a ExtRV
func (t RVInstruction_Item) AsExtRV() (ExtRV, error) {
	var body ExtRV
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExtRV overwrites any union data inside the RVInstruction_Item as the provided ExtRV
func (t *RVInstruction_Item) FromExtRV(v ExtRV) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExtRV performs a merge with any union data inside the RVInstruction_Item, using the provided ExtRV
func (t *RVInstruction_Item) MergeExtRV(v ExtRV) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RVInstruction_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RVInstruction_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /rvinfo)
	DeleteRvinfo(w http.ResponseWriter, r *http.Request)

	// (GET /rvinfo)
	GetRvinfo(w http.ResponseWriter, r *http.Request)

	// (POST /rvinfo)
	PostRvinfo(w http.ResponseWriter, r *http.Request)

	// (PUT /rvinfo)
	PutRvinfo(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteRvinfo operation middleware
func (siw *ServerInterfaceWrapper) DeleteRvinfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRvinfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRvinfo operation middleware
func (siw *ServerInterfaceWrapper) GetRvinfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRvinfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRvinfo operation middleware
func (siw *ServerInterfaceWrapper) PostRvinfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRvinfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutRvinfo operation middleware
func (siw *ServerInterfaceWrapper) PutRvinfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutRvinfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/rvinfo", wrapper.DeleteRvinfo)
	m.HandleFunc("GET "+options.BaseURL+"/rvinfo", wrapper.GetRvinfo)
	m.HandleFunc("POST "+options.BaseURL+"/rvinfo", wrapper.PostRvinfo)
	m.HandleFunc("PUT "+options.BaseURL+"/rvinfo", wrapper.PutRvinfo)

	return m
}

type DeleteRvinfoRequestObject struct {
}

type DeleteRvinfoResponseObject interface {
	VisitDeleteRvinfoResponse(w http.ResponseWriter) error
}

type DeleteRvinfo200JSONResponse RVInfo

func (response DeleteRvinfo200JSONResponse) VisitDeleteRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRvinfo401JSONResponse struct{ externalRef0.Unauthorized }

func (response DeleteRvinfo401JSONResponse) VisitDeleteRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRvinfo403JSONResponse struct{ externalRef0.Forbidden }

func (response DeleteRvinfo403JSONResponse) VisitDeleteRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRvinfo500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response DeleteRvinfo500JSONResponse) VisitDeleteRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRvinfoRequestObject struct {
}

type GetRvinfoResponseObject interface {
	VisitGetRvinfoResponse(w http.ResponseWriter) error
}

type GetRvinfo200JSONResponse RVInfo

func (response GetRvinfo200JSONResponse) VisitGetRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRvinfo401JSONResponse struct{ externalRef0.Unauthorized }

func (response GetRvinfo401JSONResponse) VisitGetRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRvinfo403JSONResponse struct{ externalRef0.Forbidden }

func (response GetRvinfo403JSONResponse) VisitGetRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRvinfo500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response GetRvinfo500JSONResponse) VisitGetRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostRvinfoRequestObject struct {
	Body *PostRvinfoJSONRequestBody
}

type PostRvinfoResponseObject interface {
	VisitPostRvinfoResponse(w http.ResponseWriter) error
}

type PostRvinfo200JSONResponse RVInfo

func (response PostRvinfo200JSONResponse) VisitPostRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRvinfo401JSONResponse struct{ externalRef0.Unauthorized }

func (response PostRvinfo401JSONResponse) VisitPostRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostRvinfo403JSONResponse struct{ externalRef0.Forbidden }

func (response PostRvinfo403JSONResponse) VisitPostRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostRvinfo500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response PostRvinfo500JSONResponse) VisitPostRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutRvinfoRequestObject struct {
	Body *PutRvinfoJSONRequestBody
}

type PutRvinfoResponseObject interface {
	VisitPutRvinfoResponse(w http.ResponseWriter) error
}

type PutRvinfo200JSONResponse RVInfo

func (response PutRvinfo200JSONResponse) VisitPutRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutRvinfo401JSONResponse struct{ externalRef0.Unauthorized }

func (response PutRvinfo401JSONResponse) VisitPutRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutRvinfo403JSONResponse struct{ externalRef0.Forbidden }

func (response PutRvinfo403JSONResponse) VisitPutRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutRvinfo500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response PutRvinfo500JSONResponse) VisitPutRvinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (DELETE /rvinfo)
	DeleteRvinfo(ctx context.Context, request DeleteRvinfoRequestObject) (DeleteRvinfoResponseObject, error)

	// (GET /rvinfo)
	GetRvinfo(ctx context.Context, request GetRvinfoRequestObject) (GetRvinfoResponseObject, error)

	// (POST /rvinfo)
	PostRvinfo(ctx context.Context, request PostRvinfoRequestObject) (PostRvinfoResponseObject, error)

	// (PUT /rvinfo)
	PutRvinfo(ctx context.Context, request PutRvinfoRequestObject) (PutRvinfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteRvinfo operation middleware
func (sh *strictHandler) DeleteRvinfo(w http.ResponseWriter, r *http.Request) {
	var request DeleteRvinfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRvinfo(ctx, request.(DeleteRvinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRvinfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRvinfoResponseObject); ok {
		if err := validResponse.VisitDeleteRvinfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRvinfo operation middleware
func (sh *strictHandler) GetRvinfo(w http.ResponseWriter, r *http.Request) {
	var request GetRvinfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRvinfo(ctx, request.(GetRvinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRvinfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRvinfoResponseObject); ok {
		if err := validResponse.VisitGetRvinfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRvinfo operation middleware
func (sh *strictHandler) PostRvinfo(w http.ResponseWriter, r *http.Request) {
	var request PostRvinfoRequestObject

	var body PostRvinfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRvinfo(ctx, request.(PostRvinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRvinfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRvinfoResponseObject); ok {
		if err := validResponse.VisitPostRvinfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutRvinfo operation middleware
func (sh *strictHandler) PutRvinfo(w http.ResponseWriter, r *http.Request) {
	var request PutRvinfoRequestObject

	var body PutRvinfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutRvinfo(ctx, request.(PutRvinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutRvinfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutRvinfoResponseObject); ok {
		if err := validResponse.VisitPutRvinfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
