// Package voucher provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package voucher

// UploadOwnerVouchersFormdataBody defines parameters for UploadOwnerVouchers.
type UploadOwnerVouchersFormdataBody = struct {
}

// UploadOwnerVouchersFormdataRequestBody defines body for UploadOwnerVouchers for application/x-www-form-urlencoded ContentType.
type UploadOwnerVouchersFormdataRequestBody = UploadOwnerVouchersFormdataBody
