name: "Build Container"
description: "Build container"
inputs:
  image-name:
    description: "The name of the container image"
    required: true
outputs:
  buildid:
    description: The build ID of this container build
    value: ${{ steps.buildid.outputs.buildid }}
  images:
    description: "Names of images that were built"
    value: ${{ steps.alltags.outputs.images }}
  tags:
    description: Image tags that were built
    value: ${{ steps.alltags.outputs.tags }}
  imagetags:
    description: "Image:tag pairs that were built"
    value: ${{ steps.alltags.outputs.imagetags }}

runs:
  using: "composite"
  steps:
  - name: Set unique build ID
    id: buildid
    shell: bash
    run: echo 'buildid=build-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}' >> $GITHUB_OUTPUT

  - name: Container Metadata
    id: container-metadata
    uses: docker/metadata-action@v4
    with:
      images: ${{ inputs.image-name }}
      tags: |
        type=edge
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=ref,event=pr
        type=schedule
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

  - name: Set all generated image build tags
    id: alltags
    shell: bash
    run: |
      echo "images=${{ inputs.image-name }}" >> $GITHUB_OUTPUT
      tags=$(echo "${{ steps.container-metadata.outputs.tags }}" | sed "s,^${{ inputs.image-name }}:,,g" | xargs)
      echo "tags=${tags}" >> $GITHUB_OUTPUT
      imagetags=$(echo "${{ steps.container-metadata.outputs.tags }}" | xargs)
      echo "imagetags=${imagetags}" >> $GITHUB_OUTPUT

  - name: Build container
    uses: redhat-actions/buildah-build@v2
    with:
      containerfiles: Dockerfile
      tags: |
        ${{ steps.container-metadata.outputs.tags }}
        ${{ inputs.image-name }}:${{ steps.buildid.outputs.buildid }}
      labels: ${{ steps.container-metadata.outputs.labels }}
      build-args: |
        BUILDID=${{ steps.buildid.outputs.buildid }}
