include:
  - fdo-onboarding-servers.yaml
services:
   new_owner:
    container_name: new_owner
    hostname: new_owner
    image: new_owner
    build: ../../..
    environment:
      TZ: Europe/Madrid
    user: ${container_user}
    command:
      - owner
      - new_owner:8045
      - --db=${container_working_dir:-/workdir}/new_owner.db
      - --db-pass='2=,%95QF<uTLLHt'
      - --debug
      - --owner-key=${container_working_dir:-/workdir}/certs/new_owner.key
      - --device-ca-cert=${container_working_dir:-/workdir}/certs/device_ca.crt
    working_dir: ${container_working_dir:-/workdir}
    networks:
      - fdo
    ports:
      - 8045:8045
    volumes:
      - ${base_dir:-./test/workdir}:${container_working_dir:-/workdir}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://new_owner:8045/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
