include:
  - fdo-networks.yaml
services:
  manufacturer:
    container_name: manufacturer
    hostname: manufacturer
    image: manufacturer
    build: ../../..
    environment:
      TZ: Europe/Madrid
    user: ${container_user}
    command:
     - --debug
     - manufacturing
     - --config=${container_working_dir:-/workdir}/configs/manufacturing.yaml
    working_dir: ${container_working_dir:-/workdir}
    volumes:
      - ${base_dir:-./test/workdir}:${container_working_dir:-/workdir}
    networks:
      - fdo
    ports:
      - 8038:8038
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://manufacturer:8038/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  rendezvous:
    container_name: rendezvous
    hostname: rendezvous
    image: rendezvous
    build: ../../..
    environment:
      TZ: Europe/Madrid
    user: ${container_user}
    command:
      - --debug
      - rendezvous
      - --config=${container_working_dir:-/workdir}/configs/rendezvous.yaml
    working_dir: ${container_working_dir:-/workdir}
    volumes:
      - ${base_dir:-./test/workdir}:${container_working_dir:-/workdir}
    networks:
      - fdo
    ports:
      - 8041:8041
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://rendezvous:8041/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  owner:
    container_name: owner
    hostname: owner
    image: owner
    build: ../../..
    environment:
      TZ: Europe/Madrid
    user: ${container_user}
    command:
      - --debug
      - owner
      - --config=${container_working_dir:-/workdir}/configs/owner.yaml
    working_dir: ${container_working_dir:-/workdir}
    volumes:
      - ${base_dir:-./test/workdir}:${container_working_dir:-/workdir}
    networks:
      - fdo
    ports:
      - 8043:8043
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://owner:8043/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
