services:
  owner:
    command:
      - owner
      - owner:8043
      - --db=${container_working_dir:-/workdir}/owner.db
      - --db-pass='2=,%95QF<uTLLHt'
      - --debug
      - --owner-key=${container_working_dir:-/workdir}/certs/owner.key
      - --device-ca-cert=${container_working_dir:-/workdir}/certs/device_ca.crt
      - --command-wget=http://wget_httpd:8888/file1
  wget_httpd:
    container_name: wget_httpd
    hostname: wget_httpd
    image: python:alpine
    environment:
      TZ: Europe/Madrid
    user: ${container_user}
    command:
      - "python3"
      - "-m"
      - "http.server"
      - "8888"
    working_dir: ${container_working_dir:-/workdir}/fsim/wget/httpd
    networks:
      - fdo
    ports:
      - 8888:8888
    volumes:
      - ${base_dir:-./test/workdir}:${container_working_dir:-/workdir}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl --silent --output /dev/null --fail http://wget_httpd:8888" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
