// Package components provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package components

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for VoucherResponseEncoding.
const (
	Pem VoucherResponseEncoding = "pem"
)

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error type identifier
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// RVTO2Addr defines model for RVTO2Addr.
type RVTO2Addr struct {
	// Rvto2addr Rendezvous TO2 address information
	Rvto2addr [][]RVTO2Addr_Rvto2addr_Item `json:"rvto2addr"`
}

// RVTO2AddrRvto2addr0 defines model for .
type RVTO2AddrRvto2addr0 = int

// RVTO2AddrRvto2addr1 defines model for .
type RVTO2AddrRvto2addr1 = string

// RVTO2Addr_Rvto2addr_Item defines model for RVTO2Addr.rvto2addr.Item.
type RVTO2Addr_Rvto2addr_Item struct {
	union json.RawMessage
}

// VoucherInsertResponse defines model for VoucherInsertResponse.
type VoucherInsertResponse struct {
	// Inserted Number of vouchers successfully inserted
	Inserted int `json:"inserted"`

	// Processed Number of vouchers processed
	Processed int `json:"processed"`
}

// VoucherResponse defines model for VoucherResponse.
type VoucherResponse struct {
	// Encoding Voucher encoding format
	Encoding VoucherResponseEncoding `json:"encoding"`

	// Voucher Base64 encoded voucher data
	Voucher string `json:"voucher"`
}

// VoucherResponseEncoding Voucher encoding format
type VoucherResponseEncoding string

// AsRVTO2AddrRvto2addr0 returns the union data inside the RVTO2Addr_Rvto2addr_Item as a RVTO2AddrRvto2addr0
func (t RVTO2Addr_Rvto2addr_Item) AsRVTO2AddrRvto2addr0() (RVTO2AddrRvto2addr0, error) {
	var body RVTO2AddrRvto2addr0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRVTO2AddrRvto2addr0 overwrites any union data inside the RVTO2Addr_Rvto2addr_Item as the provided RVTO2AddrRvto2addr0
func (t *RVTO2Addr_Rvto2addr_Item) FromRVTO2AddrRvto2addr0(v RVTO2AddrRvto2addr0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRVTO2AddrRvto2addr0 performs a merge with any union data inside the RVTO2Addr_Rvto2addr_Item, using the provided RVTO2AddrRvto2addr0
func (t *RVTO2Addr_Rvto2addr_Item) MergeRVTO2AddrRvto2addr0(v RVTO2AddrRvto2addr0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRVTO2AddrRvto2addr1 returns the union data inside the RVTO2Addr_Rvto2addr_Item as a RVTO2AddrRvto2addr1
func (t RVTO2Addr_Rvto2addr_Item) AsRVTO2AddrRvto2addr1() (RVTO2AddrRvto2addr1, error) {
	var body RVTO2AddrRvto2addr1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRVTO2AddrRvto2addr1 overwrites any union data inside the RVTO2Addr_Rvto2addr_Item as the provided RVTO2AddrRvto2addr1
func (t *RVTO2Addr_Rvto2addr_Item) FromRVTO2AddrRvto2addr1(v RVTO2AddrRvto2addr1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRVTO2AddrRvto2addr1 performs a merge with any union data inside the RVTO2Addr_Rvto2addr_Item, using the provided RVTO2AddrRvto2addr1
func (t *RVTO2Addr_Rvto2addr_Item) MergeRVTO2AddrRvto2addr1(v RVTO2AddrRvto2addr1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RVTO2Addr_Rvto2addr_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RVTO2Addr_Rvto2addr_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
