// Package resell provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package resell

// ResellRequest defines model for ResellRequest.
type ResellRequest struct {
	// NextOwnerKey Public key of the new owner in JWK format
	NextOwnerKey map[string]interface{} `json:"nextOwnerKey"`
}

// ResellResponse defines model for ResellResponse.
type ResellResponse struct {
	// ExtendedVoucher Extended voucher in PEM format
	ExtendedVoucher []byte `json:"extendedVoucher"`

	// Guid GUID of the resold voucher
	Guid *string `json:"guid,omitempty"`

	// Success Whether the resell operation was successful
	Success bool `json:"success"`
}

// ResellVoucherJSONRequestBody defines body for ResellVoucher for application/json ContentType.
type ResellVoucherJSONRequestBody = ResellRequest
