//go:build go1.22

// Package deviceca provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package deviceca

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/internal/handlers/components"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ListTrustedDeviceCACertsParamsSortBy.
const (
	CreatedAt ListTrustedDeviceCACertsParamsSortBy = "createdAt"
	NotAfter  ListTrustedDeviceCACertsParamsSortBy = "notAfter"
)

// Defines values for ListTrustedDeviceCACertsParamsSortOrder.
const (
	Asc  ListTrustedDeviceCACertsParamsSortOrder = "asc"
	Desc ListTrustedDeviceCACertsParamsSortOrder = "desc"
)

// TrustedDeviceCACert defines model for TrustedDeviceCACert.
type TrustedDeviceCACert struct {
	// CreatedAt The timestamp when the certificate was added.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Id The unique identifier for the trusted device CA.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Issuer The issuer distinguished name of the certificate.
	Issuer *string `json:"issuer,omitempty"`

	// NotAfter The end date of the certificate's validity period.
	NotAfter *time.Time `json:"notAfter,omitempty"`

	// NotBefore The start date of the certificate's validity period.
	NotBefore *time.Time `json:"notBefore,omitempty"`

	// Pem The full certificate content in PEM format.
	Pem *string `json:"pem,omitempty"`

	// Subject The subject distinguished name of the certificate.
	Subject *string `json:"subject,omitempty"`

	// UpdatedAt The timestamp when the certificate was last updated.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// TrustedDeviceCACerts defines model for TrustedDeviceCACerts.
type TrustedDeviceCACerts struct {
	Data *[]TrustedDeviceCACert `json:"data,omitempty"`

	// Limit The number of items returned in this response.
	Limit *int `json:"limit,omitempty"`

	// Offset The offset from the beginning of the collection.
	Offset *int `json:"offset,omitempty"`

	// Total Total number of trusted device CA certificates available.
	Total *int `json:"total,omitempty"`
}

// ListTrustedDeviceCACertsParams defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParams struct {
	// Limit The number of items to return per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Issuer Filters the results by the exact issuer distinguished name.
	Issuer *string `form:"issuer,omitempty" json:"issuer,omitempty"`

	// SortBy Sorts the results by the specified field.
	SortBy *ListTrustedDeviceCACertsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Specifies the sorting order.
	SortOrder *ListTrustedDeviceCACertsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListTrustedDeviceCACertsParamsSortBy defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParamsSortBy string

// ListTrustedDeviceCACertsParamsSortOrder defines parameters for ListTrustedDeviceCACerts.
type ListTrustedDeviceCACertsParamsSortOrder string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all trusted device CA certificates
	// (GET /device-ca)
	ListTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request, params ListTrustedDeviceCACertsParams)
	// Create a new trusted device CA certificate
	// (POST /device-ca)
	CreateTrustedDeviceCACert(w http.ResponseWriter, r *http.Request)
	// Delete a trusted device CA certificate by ID
	// (DELETE /device-ca/{UUID})
	DeleteTrustedDeviceCACert(w http.ResponseWriter, r *http.Request, uuid externalRef0.UUID)
	// Get a trusted device CA certificate by ID in PEM format
	// (GET /device-ca/{UUID})
	GetTrustedDeviceCACertByIdAsPem(w http.ResponseWriter, r *http.Request, uuid externalRef0.UUID)
	// Update a trusted device CA certificate by ID
	// (PUT /device-ca/{UUID})
	UpdateTrustedDeviceCACert(w http.ResponseWriter, r *http.Request, uuid externalRef0.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTrustedDeviceCACerts operation middleware
func (siw *ServerInterfaceWrapper) ListTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTrustedDeviceCACertsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "issuer" -------------

	err = runtime.BindQueryParameter("form", true, false, "issuer", r.URL.Query(), &params.Issuer)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "issuer", Err: err})
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", r.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortOrder", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrustedDeviceCACerts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrustedDeviceCACert operation middleware
func (siw *ServerInterfaceWrapper) CreateTrustedDeviceCACert(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrustedDeviceCACert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrustedDeviceCACert operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrustedDeviceCACert(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "UUID" -------------
	var uuid externalRef0.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "UUID", r.PathValue("UUID"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "UUID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrustedDeviceCACert(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrustedDeviceCACertByIdAsPem operation middleware
func (siw *ServerInterfaceWrapper) GetTrustedDeviceCACertByIdAsPem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "UUID" -------------
	var uuid externalRef0.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "UUID", r.PathValue("UUID"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "UUID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrustedDeviceCACertByIdAsPem(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrustedDeviceCACert operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrustedDeviceCACert(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "UUID" -------------
	var uuid externalRef0.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "UUID", r.PathValue("UUID"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "UUID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrustedDeviceCACert(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/device-ca", wrapper.ListTrustedDeviceCACerts)
	m.HandleFunc("POST "+options.BaseURL+"/device-ca", wrapper.CreateTrustedDeviceCACert)
	m.HandleFunc("DELETE "+options.BaseURL+"/device-ca/{UUID}", wrapper.DeleteTrustedDeviceCACert)
	m.HandleFunc("GET "+options.BaseURL+"/device-ca/{UUID}", wrapper.GetTrustedDeviceCACertByIdAsPem)
	m.HandleFunc("PUT "+options.BaseURL+"/device-ca/{UUID}", wrapper.UpdateTrustedDeviceCACert)

	return m
}

type ListTrustedDeviceCACertsRequestObject struct {
	Params ListTrustedDeviceCACertsParams
}

type ListTrustedDeviceCACertsResponseObject interface {
	VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error
}

type ListTrustedDeviceCACerts200JSONResponse TrustedDeviceCACerts

func (response ListTrustedDeviceCACerts200JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts401JSONResponse struct{ externalRef0.Unauthorized }

func (response ListTrustedDeviceCACerts401JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts403JSONResponse struct{ externalRef0.Forbidden }

func (response ListTrustedDeviceCACerts403JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListTrustedDeviceCACerts500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response ListTrustedDeviceCACerts500JSONResponse) VisitListTrustedDeviceCACertsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTrustedDeviceCACertRequestObject struct {
	Body io.Reader
}

type CreateTrustedDeviceCACertResponseObject interface {
	VisitCreateTrustedDeviceCACertResponse(w http.ResponseWriter) error
}

type CreateTrustedDeviceCACert201JSONResponse TrustedDeviceCACert

func (response CreateTrustedDeviceCACert201JSONResponse) VisitCreateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTrustedDeviceCACert400JSONResponse struct{ externalRef0.BadRequest }

func (response CreateTrustedDeviceCACert400JSONResponse) VisitCreateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTrustedDeviceCACert401JSONResponse struct{ externalRef0.Unauthorized }

func (response CreateTrustedDeviceCACert401JSONResponse) VisitCreateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTrustedDeviceCACert403JSONResponse struct{ externalRef0.Forbidden }

func (response CreateTrustedDeviceCACert403JSONResponse) VisitCreateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateTrustedDeviceCACert500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response CreateTrustedDeviceCACert500JSONResponse) VisitCreateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACertRequestObject struct {
	UUID externalRef0.UUID `json:"UUID"`
}

type DeleteTrustedDeviceCACertResponseObject interface {
	VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error
}

type DeleteTrustedDeviceCACert204Response struct {
}

func (response DeleteTrustedDeviceCACert204Response) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTrustedDeviceCACert401JSONResponse struct{ externalRef0.Unauthorized }

func (response DeleteTrustedDeviceCACert401JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACert403JSONResponse struct{ externalRef0.Forbidden }

func (response DeleteTrustedDeviceCACert403JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACert404JSONResponse struct{ externalRef0.NotFound }

func (response DeleteTrustedDeviceCACert404JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTrustedDeviceCACert500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response DeleteTrustedDeviceCACert500JSONResponse) VisitDeleteTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByIdAsPemRequestObject struct {
	UUID externalRef0.UUID `json:"UUID"`
}

type GetTrustedDeviceCACertByIdAsPemResponseObject interface {
	VisitGetTrustedDeviceCACertByIdAsPemResponse(w http.ResponseWriter) error
}

type GetTrustedDeviceCACertByIdAsPem200ApplicationxPemFileResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetTrustedDeviceCACertByIdAsPem200ApplicationxPemFileResponse) VisitGetTrustedDeviceCACertByIdAsPemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-pem-file")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetTrustedDeviceCACertByIdAsPem401JSONResponse struct{ externalRef0.Unauthorized }

func (response GetTrustedDeviceCACertByIdAsPem401JSONResponse) VisitGetTrustedDeviceCACertByIdAsPemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByIdAsPem403JSONResponse struct{ externalRef0.Forbidden }

func (response GetTrustedDeviceCACertByIdAsPem403JSONResponse) VisitGetTrustedDeviceCACertByIdAsPemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByIdAsPem404JSONResponse struct{ externalRef0.NotFound }

func (response GetTrustedDeviceCACertByIdAsPem404JSONResponse) VisitGetTrustedDeviceCACertByIdAsPemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTrustedDeviceCACertByIdAsPem500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response GetTrustedDeviceCACertByIdAsPem500JSONResponse) VisitGetTrustedDeviceCACertByIdAsPemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTrustedDeviceCACertRequestObject struct {
	UUID externalRef0.UUID `json:"UUID"`
	Body io.Reader
}

type UpdateTrustedDeviceCACertResponseObject interface {
	VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error
}

type UpdateTrustedDeviceCACert200JSONResponse TrustedDeviceCACert

func (response UpdateTrustedDeviceCACert200JSONResponse) VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTrustedDeviceCACert400JSONResponse struct{ externalRef0.BadRequest }

func (response UpdateTrustedDeviceCACert400JSONResponse) VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTrustedDeviceCACert401JSONResponse struct{ externalRef0.Unauthorized }

func (response UpdateTrustedDeviceCACert401JSONResponse) VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTrustedDeviceCACert403JSONResponse struct{ externalRef0.Forbidden }

func (response UpdateTrustedDeviceCACert403JSONResponse) VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTrustedDeviceCACert404JSONResponse struct{ externalRef0.NotFound }

func (response UpdateTrustedDeviceCACert404JSONResponse) VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTrustedDeviceCACert500JSONResponse struct {
	externalRef0.InternalServerError
}

func (response UpdateTrustedDeviceCACert500JSONResponse) VisitUpdateTrustedDeviceCACertResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all trusted device CA certificates
	// (GET /device-ca)
	ListTrustedDeviceCACerts(ctx context.Context, request ListTrustedDeviceCACertsRequestObject) (ListTrustedDeviceCACertsResponseObject, error)
	// Create a new trusted device CA certificate
	// (POST /device-ca)
	CreateTrustedDeviceCACert(ctx context.Context, request CreateTrustedDeviceCACertRequestObject) (CreateTrustedDeviceCACertResponseObject, error)
	// Delete a trusted device CA certificate by ID
	// (DELETE /device-ca/{UUID})
	DeleteTrustedDeviceCACert(ctx context.Context, request DeleteTrustedDeviceCACertRequestObject) (DeleteTrustedDeviceCACertResponseObject, error)
	// Get a trusted device CA certificate by ID in PEM format
	// (GET /device-ca/{UUID})
	GetTrustedDeviceCACertByIdAsPem(ctx context.Context, request GetTrustedDeviceCACertByIdAsPemRequestObject) (GetTrustedDeviceCACertByIdAsPemResponseObject, error)
	// Update a trusted device CA certificate by ID
	// (PUT /device-ca/{UUID})
	UpdateTrustedDeviceCACert(ctx context.Context, request UpdateTrustedDeviceCACertRequestObject) (UpdateTrustedDeviceCACertResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListTrustedDeviceCACerts operation middleware
func (sh *strictHandler) ListTrustedDeviceCACerts(w http.ResponseWriter, r *http.Request, params ListTrustedDeviceCACertsParams) {
	var request ListTrustedDeviceCACertsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTrustedDeviceCACerts(ctx, request.(ListTrustedDeviceCACertsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTrustedDeviceCACerts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTrustedDeviceCACertsResponseObject); ok {
		if err := validResponse.VisitListTrustedDeviceCACertsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTrustedDeviceCACert operation middleware
func (sh *strictHandler) CreateTrustedDeviceCACert(w http.ResponseWriter, r *http.Request) {
	var request CreateTrustedDeviceCACertRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTrustedDeviceCACert(ctx, request.(CreateTrustedDeviceCACertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTrustedDeviceCACert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTrustedDeviceCACertResponseObject); ok {
		if err := validResponse.VisitCreateTrustedDeviceCACertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTrustedDeviceCACert operation middleware
func (sh *strictHandler) DeleteTrustedDeviceCACert(w http.ResponseWriter, r *http.Request, uuid externalRef0.UUID) {
	var request DeleteTrustedDeviceCACertRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTrustedDeviceCACert(ctx, request.(DeleteTrustedDeviceCACertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTrustedDeviceCACert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTrustedDeviceCACertResponseObject); ok {
		if err := validResponse.VisitDeleteTrustedDeviceCACertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTrustedDeviceCACertByIdAsPem operation middleware
func (sh *strictHandler) GetTrustedDeviceCACertByIdAsPem(w http.ResponseWriter, r *http.Request, uuid externalRef0.UUID) {
	var request GetTrustedDeviceCACertByIdAsPemRequestObject

	request.UUID = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrustedDeviceCACertByIdAsPem(ctx, request.(GetTrustedDeviceCACertByIdAsPemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrustedDeviceCACertByIdAsPem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTrustedDeviceCACertByIdAsPemResponseObject); ok {
		if err := validResponse.VisitGetTrustedDeviceCACertByIdAsPemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTrustedDeviceCACert operation middleware
func (sh *strictHandler) UpdateTrustedDeviceCACert(w http.ResponseWriter, r *http.Request, uuid externalRef0.UUID) {
	var request UpdateTrustedDeviceCACertRequestObject

	request.UUID = uuid

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTrustedDeviceCACert(ctx, request.(UpdateTrustedDeviceCACertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTrustedDeviceCACert")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTrustedDeviceCACertResponseObject); ok {
		if err := validResponse.VisitUpdateTrustedDeviceCACertResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
