// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for OwnerRedirectProtocol.
const (
	Http  OwnerRedirectProtocol = "http"
	Https OwnerRedirectProtocol = "https"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// OwnerRedirect defines model for OwnerRedirect.
type OwnerRedirect = []struct {
	Dns      string                `json:"dns"`
	Port     string                `json:"port"`
	Protocol OwnerRedirectProtocol `json:"protocol"`
}

// OwnerRedirectProtocol defines model for OwnerRedirect.Protocol.
type OwnerRedirectProtocol string

// VoucherInsertResponse defines model for VoucherInsertResponse.
type VoucherInsertResponse struct {
	Errors    *[]string `json:"errors,omitempty"`
	Inserted  int       `json:"inserted"`
	Processed int       `json:"processed"`
}

// VoucherMetadata defines model for VoucherMetadata.
type VoucherMetadata struct {
	CreatedAt  time.Time  `json:"created_at"`
	DeviceInfo string     `json:"device_info"`
	Guid       string     `json:"guid"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// VoucherResponse defines model for VoucherResponse.
type VoucherResponse struct {
	Encoding string `json:"encoding"`
	Guid     string `json:"guid"`
	Voucher  string `json:"voucher"`
}

// GetVouchersParams defines parameters for GetVouchers.
type GetVouchersParams struct {
	Guid       *string `form:"guid,omitempty" json:"guid,omitempty"`
	DeviceInfo *string `form:"device_info,omitempty" json:"device_info,omitempty"`
}

// PostOwnerRedirectJSONRequestBody defines body for PostOwnerRedirect for application/json ContentType.
type PostOwnerRedirectJSONRequestBody = OwnerRedirect

// PutOwnerRedirectJSONRequestBody defines body for PutOwnerRedirect for application/json ContentType.
type PutOwnerRedirectJSONRequestBody = OwnerRedirect

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /owner/redirect)
	GetOwnerRedirect(w http.ResponseWriter, r *http.Request)

	// (POST /owner/redirect)
	PostOwnerRedirect(w http.ResponseWriter, r *http.Request)

	// (PUT /owner/redirect)
	PutOwnerRedirect(w http.ResponseWriter, r *http.Request)

	// (POST /owner/resell/{guid})
	PostOwnerResellGuid(w http.ResponseWriter, r *http.Request, guid string)

	// (POST /owner/vouchers)
	PostOwnerVouchers(w http.ResponseWriter, r *http.Request)

	// (GET /vouchers)
	GetVouchers(w http.ResponseWriter, r *http.Request, params GetVouchersParams)

	// (GET /vouchers/{guid})
	GetVouchersGuid(w http.ResponseWriter, r *http.Request, guid string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /owner/redirect)
func (_ Unimplemented) GetOwnerRedirect(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /owner/redirect)
func (_ Unimplemented) PostOwnerRedirect(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /owner/redirect)
func (_ Unimplemented) PutOwnerRedirect(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /owner/resell/{guid})
func (_ Unimplemented) PostOwnerResellGuid(w http.ResponseWriter, r *http.Request, guid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /owner/vouchers)
func (_ Unimplemented) PostOwnerVouchers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /vouchers)
func (_ Unimplemented) GetVouchers(w http.ResponseWriter, r *http.Request, params GetVouchersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /vouchers/{guid})
func (_ Unimplemented) GetVouchersGuid(w http.ResponseWriter, r *http.Request, guid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOwnerRedirect operation middleware
func (siw *ServerInterfaceWrapper) GetOwnerRedirect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOwnerRedirect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOwnerRedirect operation middleware
func (siw *ServerInterfaceWrapper) PostOwnerRedirect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOwnerRedirect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutOwnerRedirect operation middleware
func (siw *ServerInterfaceWrapper) PutOwnerRedirect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutOwnerRedirect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOwnerResellGuid operation middleware
func (siw *ServerInterfaceWrapper) PostOwnerResellGuid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", chi.URLParam(r, "guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOwnerResellGuid(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOwnerVouchers operation middleware
func (siw *ServerInterfaceWrapper) PostOwnerVouchers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOwnerVouchers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVouchers operation middleware
func (siw *ServerInterfaceWrapper) GetVouchers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVouchersParams

	// ------------- Optional query parameter "guid" -------------

	err = runtime.BindQueryParameter("form", true, false, "guid", r.URL.Query(), &params.Guid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	// ------------- Optional query parameter "device_info" -------------

	err = runtime.BindQueryParameter("form", true, false, "device_info", r.URL.Query(), &params.DeviceInfo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_info", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVouchers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVouchersGuid operation middleware
func (siw *ServerInterfaceWrapper) GetVouchersGuid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guid" -------------
	var guid string

	err = runtime.BindStyledParameterWithOptions("simple", "guid", chi.URLParam(r, "guid"), &guid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVouchersGuid(w, r, guid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/owner/redirect", wrapper.GetOwnerRedirect)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/owner/redirect", wrapper.PostOwnerRedirect)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/owner/redirect", wrapper.PutOwnerRedirect)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/owner/resell/{guid}", wrapper.PostOwnerResellGuid)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/owner/vouchers", wrapper.PostOwnerVouchers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vouchers", wrapper.GetVouchers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vouchers/{guid}", wrapper.GetVouchersGuid)
	})

	return r
}
