openapi: 3.0.3
info:
  title: FDO Owner Server API
  version: 1.1.0

paths:
  # Shared endpoint used by all FDO servers (owner, manufacturer, rendezvous)
  /health:
    $ref: './shared/paths/health.yaml'

  # Owner-specific endpoints
  /owner/vouchers:
    post:
      requestBody:
        content:
          application/x-pem-file:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Vouchers processed
          content:
            application/json:
              schema:
                $ref: 'shared/schemas/common.yaml#/components/schemas/VoucherInsertResponse'

  /owner/redirect:
    get:
      responses:
        '200':
          description: Owner redirect configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnerRedirect'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnerRedirect'
      responses:
        '201':
          description: Owner redirect configuration created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnerRedirect'
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnerRedirect'
      responses:
        '200':
          description: Owner redirect configuration updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnerRedirect'

  # Shared voucher endpoints (used by manufacturer and owner servers)  
  /vouchers:
    $ref: './shared/paths/vouchers.yaml#/~1vouchers'

  /vouchers/{guid}:
    $ref: './shared/paths/vouchers.yaml#/~1vouchers~1{guid}'

  /owner/resell/{guid}:
    post:
      parameters:
        - name: guid
          in: path
          required: true
          schema: {type: string, pattern: '^[0-9a-fA-F]{32}$'}
      requestBody:
        content:
          application/x-pem-file: {schema: {type: string, format: binary}}
      responses:
        '200':
          description: Resold voucher in requested format
          content:
            application/json:
              schema: 
                $ref: 'shared/schemas/common.yaml#/components/schemas/VoucherResponse'
            application/x-pem-file:
              schema:
                type: string
                format: binary
                description: PEM-encoded ownership voucher for backward compatibility

components:
  schemas:
    # Only owner-specific schemas - shared schemas are in shared/schemas/common.yaml
    OwnerRedirect:
      type: array
      items:
        type: object
        required: [dns, port, protocol]
        properties:
          dns:
            type: string
          ip:
            type: string
            description: IP address for the redirect target
          port:
            type: string
          protocol:
            type: string
            enum: [tcp, tls, http, coap, https, coaps]
            description: Transport protocol as defined by FDO specification

