// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// VoucherInsertResponse defines model for VoucherInsertResponse.
type VoucherInsertResponse struct {
	Errors    *[]string `json:"errors,omitempty"`
	Inserted  int       `json:"inserted"`
	Processed int       `json:"processed"`
}

// VoucherMetadata defines model for VoucherMetadata.
type VoucherMetadata struct {
	CreatedAt  time.Time  `json:"created_at"`
	DeviceInfo string     `json:"device_info"`
	Guid       string     `json:"guid"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// VoucherResponse defines model for VoucherResponse.
type VoucherResponse struct {
	Encoding string `json:"encoding"`
	Guid     string `json:"guid"`
	Voucher  string `json:"voucher"`
}
