services:
  go-fdo-client:
    container_name: go-fdo-client
    hostname: go-fdo-client
    image: go-fdo-client
    build: https://github.com/fido-device-onboard/go-fdo-client.git#main
    working_dir: ${container_working_dir:-/workdir}/device-credentials
    user: "${container_user}"
    networks:
      - fdo
    volumes:
      - ${base_dir:-./test/workdir}:${container_working_dir:-/workdir}
    restart: no
networks:
  fdo:
    name: fdo
    external: true
