// Package health provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package health

// Defines values for HealthResponseStatus.
const (
	Healthy HealthResponseStatus = "healthy"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Health status
	Status HealthResponseStatus `json:"status"`

	// Version Service version
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus Health status
type HealthResponseStatus string
