openapi: 3.0.3
info:
  title: FDO Shared Schemas
  version: 1.0.0
  description: Shared schemas used across multiple FDO servers (owner, manufacturer, rendezvous)

paths:
  /_internal/schema-types:
    get:
      responses:
        '200':
          description: Internal endpoint for shared type generation - not a real API endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    $ref: '#/components/schemas/HealthResponse'
                  voucher:
                    $ref: '#/components/schemas/VoucherResponse'
                  metadata:
                    $ref: '#/components/schemas/VoucherMetadata'
                  insert:
                    $ref: '#/components/schemas/VoucherInsertResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required: [version, status]
      properties:
        version:
          type: string
        status:
          type: string

    VoucherResponse:
      type: object
      required: [voucher, encoding, guid]
      properties:
        voucher:
          type: string
        encoding:
          type: string
        guid:
          type: string

    VoucherMetadata:
      type: object
      required: [guid, device_info, created_at]
      properties:
        guid:
          type: string
        device_info:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    VoucherInsertResponse:
      type: object
      required: [processed, inserted]
      properties:
        processed:
          type: integer
        inserted:
          type: integer
        errors:
          type: array
          items:
            type: string