openapi: 3.0.0
info:
  title: Common API Objects
  version: 1.0.0
  description: Common components, schemas, security definitions, and reusable response objects used across all FDO server APIs.
  contact:
    name: Go FDO Server API Support
    url: https://github.com/fido-device-onboard/go-fdo-server/issues
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication using username and password.
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer Token authentication. The token can be a JWT or an opaque token.
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API Key authentication via the X-API-Key header.
    OidcAuth:
      type: openIdConnect
      openIdConnectUrl: https://auth.example.com/realms/fdo/.well-known/openid-configuration
      description: OpenID Connect authentication using a JWT obtained from an OIDC provider. The openIdConnectUrl should be configured to point to your OIDC provider's discovery endpoint.
    Oauth2Auth:
      type: oauth2
      description: OAuth 2.0 authentication. The tokenUrl should be configured to point to your OAuth2 provider's token endpoint.
      flows:
        clientCredentials:
          tokenUrl: https://auth.example.com/realms/fdo/protocol/openid-connect/token
          scopes:
            'read:device-ca-certs': "Grants read access to trusted device CA certificates."
            'write:device-ca-certs': "Grants create, update, and delete access to trusted device CA certificates."
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A human-readable error message.
  responses:
    BadRequest:
      description: Bad Request - The request was malformed or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            badRequest:
              summary: Example of a bad request error
              value:
                message: "Invalid Request."
    Unauthorized:
      description: Unauthorized - Authentication credentials missing, invalid, or expired.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            unauthorized:
              summary: Example of an unauthorized error
              value:
                message: "Authentication token is invalid or has expired."
    Forbidden:
      description: Forbidden - The authenticated user does not have permission to perform this action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            forbidden:
              summary: Example of a forbidden error
              value:
                message: "User does not have the right access level."
    NotFound:
      description: Not Found - The requested resource does not exist.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            notFound:
              summary: Example of a not found error
              value:
                message: "Object not found."
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            serverError:
              summary: Example of a server error
              value:
                message: "An unexpected error occurred."
