//go:build go1.22

// Package rvinfo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rvinfo

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "github.com/fido-device-onboard/go-fdo-server/api/v1/components"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// CreateRendezvousInfoJSONRequestBody defines body for CreateRendezvousInfo for application/json ContentType.
type CreateRendezvousInfoJSONRequestBody = externalRef0.RVInfo

// UpdateRendezvousInfoJSONRequestBody defines body for UpdateRendezvousInfo for application/json ContentType.
type UpdateRendezvousInfoJSONRequestBody = externalRef0.RVInfo

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the current RendezvousInfo (Deprecated)
	// (GET /rvinfo)
	GetRendezvousInfo(w http.ResponseWriter, r *http.Request)
	// Create the RendezvousInfo configuration (Deprecated)
	// (POST /rvinfo)
	CreateRendezvousInfo(w http.ResponseWriter, r *http.Request)
	// Update the RendezvousInfo configuration (Deprecated)
	// (PUT /rvinfo)
	UpdateRendezvousInfo(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetRendezvousInfo operation middleware
func (siw *ServerInterfaceWrapper) GetRendezvousInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRendezvousInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRendezvousInfo operation middleware
func (siw *ServerInterfaceWrapper) CreateRendezvousInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRendezvousInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRendezvousInfo operation middleware
func (siw *ServerInterfaceWrapper) UpdateRendezvousInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRendezvousInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/rvinfo", wrapper.GetRendezvousInfo)
	m.HandleFunc("POST "+options.BaseURL+"/rvinfo", wrapper.CreateRendezvousInfo)
	m.HandleFunc("PUT "+options.BaseURL+"/rvinfo", wrapper.UpdateRendezvousInfo)

	return m
}

type GetRendezvousInfoRequestObject struct {
}

type GetRendezvousInfoResponseObject interface {
	VisitGetRendezvousInfoResponse(w http.ResponseWriter) error
}

type GetRendezvousInfo200JSONResponse externalRef0.RVInfo

func (response GetRendezvousInfo200JSONResponse) VisitGetRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRendezvousInfo404TextResponse externalRef0.ErrorString

func (response GetRendezvousInfo404TextResponse) VisitGetRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type GetRendezvousInfo500TextResponse externalRef0.ErrorString

func (response GetRendezvousInfo500TextResponse) VisitGetRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRendezvousInfoRequestObject struct {
	Body *CreateRendezvousInfoJSONRequestBody
}

type CreateRendezvousInfoResponseObject interface {
	VisitCreateRendezvousInfoResponse(w http.ResponseWriter) error
}

type CreateRendezvousInfo201JSONResponse externalRef0.RVInfo

func (response CreateRendezvousInfo201JSONResponse) VisitCreateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRendezvousInfo400TextResponse externalRef0.ErrorString

func (response CreateRendezvousInfo400TextResponse) VisitCreateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRendezvousInfo409TextResponse externalRef0.ErrorString

func (response CreateRendezvousInfo409TextResponse) VisitCreateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(409)

	_, err := w.Write([]byte(response))
	return err
}

type CreateRendezvousInfo500TextResponse externalRef0.ErrorString

func (response CreateRendezvousInfo500TextResponse) VisitCreateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRendezvousInfoRequestObject struct {
	Body *UpdateRendezvousInfoJSONRequestBody
}

type UpdateRendezvousInfoResponseObject interface {
	VisitUpdateRendezvousInfoResponse(w http.ResponseWriter) error
}

type UpdateRendezvousInfo200JSONResponse externalRef0.RVInfo

func (response UpdateRendezvousInfo200JSONResponse) VisitUpdateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRendezvousInfo400TextResponse externalRef0.ErrorString

func (response UpdateRendezvousInfo400TextResponse) VisitUpdateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRendezvousInfo404TextResponse externalRef0.ErrorString

func (response UpdateRendezvousInfo404TextResponse) VisitUpdateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateRendezvousInfo500TextResponse externalRef0.ErrorString

func (response UpdateRendezvousInfo500TextResponse) VisitUpdateRendezvousInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get the current RendezvousInfo (Deprecated)
	// (GET /rvinfo)
	GetRendezvousInfo(ctx context.Context, request GetRendezvousInfoRequestObject) (GetRendezvousInfoResponseObject, error)
	// Create the RendezvousInfo configuration (Deprecated)
	// (POST /rvinfo)
	CreateRendezvousInfo(ctx context.Context, request CreateRendezvousInfoRequestObject) (CreateRendezvousInfoResponseObject, error)
	// Update the RendezvousInfo configuration (Deprecated)
	// (PUT /rvinfo)
	UpdateRendezvousInfo(ctx context.Context, request UpdateRendezvousInfoRequestObject) (UpdateRendezvousInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetRendezvousInfo operation middleware
func (sh *strictHandler) GetRendezvousInfo(w http.ResponseWriter, r *http.Request) {
	var request GetRendezvousInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRendezvousInfo(ctx, request.(GetRendezvousInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRendezvousInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRendezvousInfoResponseObject); ok {
		if err := validResponse.VisitGetRendezvousInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRendezvousInfo operation middleware
func (sh *strictHandler) CreateRendezvousInfo(w http.ResponseWriter, r *http.Request) {
	var request CreateRendezvousInfoRequestObject

	var body CreateRendezvousInfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRendezvousInfo(ctx, request.(CreateRendezvousInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRendezvousInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRendezvousInfoResponseObject); ok {
		if err := validResponse.VisitCreateRendezvousInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRendezvousInfo operation middleware
func (sh *strictHandler) UpdateRendezvousInfo(w http.ResponseWriter, r *http.Request) {
	var request UpdateRendezvousInfoRequestObject

	var body UpdateRendezvousInfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRendezvousInfo(ctx, request.(UpdateRendezvousInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRendezvousInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRendezvousInfoResponseObject); ok {
		if err := validResponse.VisitUpdateRendezvousInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
