openapi: 3.0.3
info:
  title: FDO Server - Health API
  version: 1.0.0
  description: Health check endpoints

paths:
  /health:
    get:
      summary: Health check
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: ["healthy"]
          description: Health status
        version:
          type: string
          description: Service version