on:
  push:
    branches:
    - main
  pull_request:

name: Continuous integration

jobs:
  test-makefile:
    name: build and test makefile
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Generate certs
        run: |
          source test/test-makefile.sh
          generate_certs

      - name: Build and install the binary
        run: |
          source test/test-makefile.sh
          install_server

      - name: Fail if the source code has changes after build
        uses: NathanielHill/fail-if-changes@master

      - name: Build and install 'go-fdo-client'
        run: |
          source test/test-makefile.sh
          install_client

      - name: Setup the environment
        id: setup_env
        run: |
          source test/test-makefile.sh
          setup_env

      - name: Test FIDO Device Onboarding
        run: |
          source test/test-makefile.sh
          test_onboarding

      - name: Test FIDO Resale Protocol
        run: |
          source test/test-makefile.sh
          test_resale

      - name: Get Manufacturer, Rendezvous and Owner server logs after a failed onboarding
        if: failure() && steps.setup_env.outcome == 'success'
        run: |
          source test/test-makefile.sh
          get_server_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/test-makefile.sh
          cleanup

  test-container:
    name: build and test containers
    runs-on: ubuntu-latest
    steps:

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Generate certs
        run: |
          source test/test-container.sh
          generate_certs

      - name: Build and install the binary
        run: |
          source test/test-container.sh
          install_server

      - name: Make sure there are no changes after build
        uses: NathanielHill/fail-if-changes@master

      - name: Build and install 'go-fdo-client'
        run: |
          source test/test-container.sh
          install_client

      - name: Setup the environment
        id: setup_env
        run: |
          source test/test-container.sh
          setup_env

      - name: Test FIDO Device Onboarding
        run: |
          source test/test-container.sh
          test_onboarding

      - name: Test FIDO Resale Protocol
        run: |
          source test/test-container.sh
          test_resale

      - name: Get Manufacturer, Rendezvous and Owner server logs after a failed onboarding
        if: failure() && steps.setup_env.outcome == 'success'
        run: |
          source test/test-container.sh
          get_server_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/test-container.sh
          cleanup

  test-rpms:
    name: build srpm and rpms
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install dependencies
        run: dnf install -y git make node

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build SRPM
        run: |
          git config --global --add safe.directory /__w/go-fdo-server/go-fdo-server
          make srpm

      - name: Build RPM
        run: |
          git config --global --add safe.directory /__w/go-fdo-server/go-fdo-server
          make rpm

      - name: Fail if the source code has changes after build
        uses: NathanielHill/fail-if-changes@master

  test-fsim-wget:
    name: test the wget FSIM functionality
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run the wget FSIM
        run: |
          source test/test-fsim-wget.sh
          test_fsim_wget

      - name: Get Manufacturer, Rendezvous and Owner server logs after a failed onboarding
        if: failure()
        run: |
          source test/test-fsim-wget.sh
          get_server_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source test/test-fsim-wget.sh
          cleanup_wget
