on:
  push:
    branches:
    - main
  pull_request:

name: Continuous integration

jobs:
  check-spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: codespell-project/actions-codespell@master
        with:
          builtin: clear,rare,usage,code,en-GB_to_en-US
          check_filenames: true
          check_hidden: true
          ignore_words_file: .github/spellcheck-ignore
          skip: "./docs/Gemfile.lock,./docs/_config.yml,./.github,./.git"

  gofmt:
    name: Gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: if [ "$(gofmt -d -s -l . | tee /dev/stderr | wc -l)" -gt 0 ]; then exit 1; fi

  check_onboarding:
    name: Smoke onboarding test
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install deps
        run: |
          dnf install -y git awk
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Fix git trust
        run: git config --global --add safe.directory /__w/go-fdo-server/go-fdo-server
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go install .
      - name: Test with the Go CLI
        run: go test
      - name: Test API handlers
        run: go test -v ./api/handlersTest
      - run: "go vet ./..."
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
      - name: Smoke test onboarding
        run: ./smoke-test.sh

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install commitlint dependencies
        run: npm install commitlint
      - uses: wagoid/commitlint-github-action@v6
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          configFile: .github/commitlint.config.mjs
          failOnWarnings: true